version: 0.0
os: windows
files:
  - source: \
    destination: C:\temp\TestAPIProject
  
hooks:
  ApplicationStop:
    - location: deploy-scripts\application-stop.ps1
  BeforeInstall:
    - location: deploy-scripts\before-install.ps1
  ApplicationStart:
    - location: deploy-scripts\application-start.ps1