version: 0.0
os: windows
files:
  - source: \
    destination: C:\temp\TestAPIProject
  
hooks:
  ApplicationStart:
    - location: deploy-scripts\PublishArtifacts.ps1
    - location: deploy-scripts\StageArtifacts.ps1
    - location: deploy-scripts\CreateWebSite.ps1